CREATE TABLE shipments
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

CREATE TABLE cargos
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_id     BIGINT         NOT NULL,
    income          DECIMAL(15, 2) NOT NULL,
    cost            DECIMAL(15, 2) NOT NULL,
    additional_cost DECIMAL(15, 2) NOT NULL,
    total_cost      DECIMAL(15, 2) NOT NULL,
    profit          DECIMAL(15, 2) NOT NULL,
    CONSTRAINT fk_profits_result_shipments
        FOREIGN KEY (shipment_id) REFERENCES shipments (id)
);